- knora/bitstreams/test.csv
Exchanged some test data with better ones
> Changed-excel

- knora/dsplib/models/value.py
- test/BUILD.bazel
- test/test_tools.py
- test/test_value.py
- testdata/test-data.xml
> test(xml upload): try to provoke error with date (DSP-1409)

- .github/workflows/ckeck-pr-title.yml
Resolves DSP-1492
Release-As: 1.1.0
> chore: allow release PRs in PR title check (DSP-1492)

- .github/workflows/ckeck-pr-title.yml
- .github/workflows/release-please.yml
> chore: bump version to 1.1.0 (DSP-1492)

- mkdocs.yml
> docs: add copyright information to docs (DSP-1190)

- docs/dsp-tools-xmlupload.md
…st-props, attribute "list" is required
> docs(dsp-tools-xmlupload): addition to incomplete paragraph (DSP-1693)

- docs/dsp-tools-usage.md
- docs/dsp-tools-xmlupload.md
- knora/dsp_tools.py
> docs(xmlupload): add documentation to verbose option (DSP-1797)

- docs/dsp-tools-xmlupload.md
> fix(release): fix skipped release after pull request #74 (DSP-1797)

- MANIFEST.in
- Makefile
- docs/dsp-tools-create.md
> fix(manifest): fix documentation and missing files (DSP-1580)

- knora/dsplib/utils/expand_all_lists.py
> fix(import): fix import error when starting script directly (DSP-1869)

- docs/dsp-tools-create.md
- knora/README.md
> docs(typo): correct typo in documentation

- .github/workflows/daily-test.yml
> test: add daily tests (DEV-61)

- knora/dsplib/utils/onto_create_ontology.py
> fix(comments): fix comments in ontology creation (DEV-250)

- docs/dsp-tools-create.md
> docs: update out-of-date example in docs (DEV-265)

- docs/dsp-tools-create.md
- knora/dsplib/models/resource.py
- knora/dsplib/schemas/ontology.json
- knora/dsplib/schemas/resources-only.json
- knora/knora.py
- testdata/test-onto.json
> feat: update to support ArchiveRepresentation (DEV-259)

- knora/dsplib/models/value.py
> fix: problem with reference to list values (DEV-356)

- docs/dsp-tools-create-ontologies.md
> docs: add isPartOf and seqnum properties to documentation (DEV-216)

- docs/dsp-tools-excel.md
> docs(dsp-tools-excel): mention the GUI order and other small improvements (DEV-99)

- knora/dsplib/utils/onto_validate.py
> feat: improve json schema validation error output (DEV-456)

- docs/dsp-tools-create-ontologies.md
- knora/dsplib/schemas/ontology.json
> feat(ontology): add Representation (DEV-551)

- knora/dsplib/utils/onto_create_ontology.py
- testdata/test-data.xml
- testdata/test-onto.json
> fix(onto creation): prevent sorting algorith from modifying original ontology

- docs/dsp-tools-usage.md
- knora/dsplib/models/connection.py
> fix(get): handle slash at end of server, improve docs (DEV-734)

- testdata/test-id2iri-data.xml
> fix(testdata): remove salsah-links from test-id2iri-data.xml (DEV-975)

- .github/workflows/release.yml
> chore: stop serving docs to dasch-swiss.github.io (DEV-825)

- docs/dsp-tools-create-ontologies.md
> docs: sort entries alphabetically (DEV-1184)

- README.md
- mkdocs.yml
> docs: fix outdated links (DEV-1194)

- .github/workflows/release.yml
> fix: fix PyPI deployment (DEV-1270)

- docs/dsp-tools-create-ontologies.md
- docs/dsp-tools-create.md
- docs/dsp-tools-excel.md
- docs/dsp-tools-usage.md
- docs/dsp-tools-xmlupload.md
- docs/index.md
- mkdocs.yml
> docs: clarify docs of onto creation (DEV-1164)

- knora/dsp_tools.py
- knora/dsplib/models/sipi.py
- knora/dsplib/utils/onto_create_ontology.py
- knora/dsplib/utils/onto_validate.py
- knora/dsplib/utils/shared_methods.py
- knora/dsplib/utils/xml_upload.py
- test/e2e/test_tools.py
- testdata/test-data-minimal.xml
> chore: minor improvements of xmlupload (DEV-1141)

- .github/workflows/tests-on-push.yml
> chore: reduce GitHub workflow frequency (DEV-1344)

- knora/dsplib/utils/start-api.sh
- knora/dsplib/utils/start-app.sh
> fix(start-app, start-api): make git handling more robust (DEV-1520)

- .github/workflows/daily-test.yml
- .github/workflows/release.yml
- .github/workflows/tests-on-push.yml
- knora/dsplib/utils/xml_upload.py
- test/e2e/test_tools.py
> chore: bump versions of GitHub actions (DEV-1532)

- knora/dsplib/docker/docker-compose.yml
> fix(start-stack): adapt version numbers of app and db (DEV-1558)

- knora/dsplib/docker/docker-compose.yml
> chore(start-api): adjust version numbers of DSP-API and DSP-APP according to 2022.11.01 (DEV-1579)

- src/dsp_tools/models/group.py
> fix: get command fails if no groups are on the server (DEV-1622)

- CHANGELOG.md
- docs/developers-git-submodules.md
- docs/dsp-tools-excel2json.md
- docs/dsp-tools-excel2xml.md
- docs/dsp-tools-usage.md
- docs/dsp-tools-xmlupload.md
- docs/index.md
> docs: fix broken links, make dsp-tools uppercase (DEV-1550)

- docs/developers/start-stack-command.md
- src/dsp_tools/docker/docker-compose.yml
- src/dsp_tools/utils/stack_handling.py
> chore: bump start-stack to 2023.02.01 (DEV-1709)

- README.md
- docs/file-formats/excel2json.md
- docs/index.md
- mkdocs.yml
- src/dsp_tools/excel2xml.py
> chore: update links according to new structure of docs (DEV-1648)

- src/dsp_tools/utils/project_validate.py
- test/unittests/test_create_project.py
- testdata/invalid_testdata/test-project-cardinalities-that-were-not-defined-in-properties-section.json
- testdata/invalid_testdata/test-project-super-property-that-was-not-defined-in-properties-section.json
- testdata/test-project-systematic.json
> fix(create): improve validation to prevent endless loop if properties are undefined (DEV-1720)

- src/dsp_tools/excel2xml.py
- test/unittests/test_excel2xml.py
> chore(excel2xml): allow PathLike for bitstream-prop (DEV-1729)

- src/dsp_tools/utils/project_create.py
> fix(create): property from other ontology not found (DEV-1381)

- testdata/test-project-enhanced-xmlupload.json
> chore: enhanced xmlupload: add test onto (DEV-1760)

- src/dsp_tools/docker/docker-compose.yml
- src/dsp_tools/utils/stack_handling.py
> chore: bump start-stack to 2023.02.02 (DEV-1732)

- src/dsp_tools/excel2xml.py
- src/dsp_tools/utils/excel_to_json_lists.py
- src/dsp_tools/utils/excel_to_json_properties.py
- src/dsp_tools/utils/excel_to_json_resources.py
- src/dsp_tools/utils/project_validate.py
> chore: beautify stack traces (DEV-1766)

- docs/cli-commands.md
- src/dsp_tools/dsp_tools.py
> refactor: harmonize CLI help texts with the CLI commands documentation (DEV-1767)

- src/dsp_tools/dsp_tools.py
- src/dsp_tools/utils/project_create.py
- src/dsp_tools/utils/project_create_lists.py
- src/dsp_tools/utils/shared.py
- test/e2e/test_tools.py
- test/unittests/test_create_project.py
> refactor: refactor list creation (DEV-1775)

- src/dsp_tools/dsp_tools.py
- src/dsp_tools/utils/id_to_iri.py
> fix: invalid argument names in CLI entrypoint (DEV-1776)

- src/dsp_tools/docker/docker-compose.yml
- src/dsp_tools/utils/stack_handling.py
- test/e2e/test_user.py
> chore: bump start-stack to 2023.03.01 (DEV-1802)

- src/dsp_tools/utils/project_create.py
- testdata/invalid_testdata/test-data-invalid-resource-tag.xml
- testdata/invalid_testdata/test-data-utf8-text-with-xml-tags.xml
- testdata/invalid_testdata/test-project-invalid-super-property.json
- testdata/test-data-minimal.xml
- testdata/test-project-minimal.json
> fix(create): allow identical onto names if they belong to different projects (DEV-1777)

- docs/cli-commands.md
> docs: use single quotes around passwords to prevent problems with special characters (DEV-1825)

- testdata/invalid-testdata/json-project/cardinalities-that-were-not-defined-in-properties-section.json
- testdata/invalid-testdata/json-project/circular-ontology.json
- testdata/invalid-testdata/json-project/invalid-super-property.json
- testdata/invalid-testdata/json-project/super-property-that-was-not-defined-in-properties-section.json
- testdata/invalid-testdata/xml-data/invalid-resource-tag.xml
- testdata/invalid-testdata/xml-data/utf8-text-with-xml-tags.xml
- testdata/json-project/test-project-minimal.json
- testdata/json-project/test-project-systematic.json
- testdata/xml-data/test-data-minimal.xml
- testdata/xml-data/test-data-systematic.xml
> fix: correct broken schema references in test data files (DEV-1832)

- src/dsp_tools/models/ontology.py
- src/dsp_tools/models/set_encoder.py
> chore: merge dublette class into one class (DEV-1831)

- docs/file-formats/json-project/ontologies.md
- src/dsp_tools/models/resourceclass.py
- src/dsp_tools/schemas/project.json
- src/dsp_tools/utils/project_create.py
- src/dsp_tools/utils/project_validate.py
- testdata/json-project/test-project-minimal.json
> feat(create): create a resource class without cardinalities (DEV-1853)

- docs/file-formats/json-project/ontologies.md
- src/dsp_tools/models/ontology.py
- src/dsp_tools/schemas/project.json
- src/dsp_tools/utils/project_create.py
- testdata/json-project/test-project-systematic.json
> fix(create, get): handle comment to ontology (DEV-1852)

- docs/file-formats/json-project/ontologies.md
- src/dsp_tools/models/propertyclass.py
- src/dsp_tools/schemas/project.json
- src/dsp_tools/schemas/properties-only.json
> fix: allow Pulldown, Radio, and List as gui_elements for lists (DEV-1810)

- docs/cli-commands.md
- docs/developers/user-data.md
- docs/index.md
- src/dsp_tools/dsp_tools.py
- src/dsp_tools/utils/project_create.py
- src/dsp_tools/utils/rosetta.py
- src/dsp_tools/utils/shared.py
- src/dsp_tools/utils/xml_upload.py
- test/e2e/test_rosetta.py
- test/unittests/test_create_project.py
> feat: check out rosetta and upload it on local stack (DEV-1842)

- src/dsp_tools/utils/xml_upload.py
- test/unittests/test_id_to_iri.py
- test/unittests/test_xmlupload.py
> refactor: minor improvements (DEV-1912)

- test/e2e/test_xmlupload.py
> test(xmlupload): add e2e test for invalid ontoname and invalid shortcode (DEV-1969)

- src/dsp_tools/utils/project_get.py
> chore(get): allow shortname to be uppercase (DEV-1972)

- poetry.lock
- pyproject.toml
> chore: bump dependencies (DEV-1960)

- src/dsp_tools/resources/start-stack/docker-compose.yml
- src/dsp_tools/utils/stack_handling.py
- test/e2e/test_user.py
> chore: bump start-stack to 2023.04.02 (DEV-1933)

- src/dsp_tools/models/connection.py
- src/dsp_tools/models/exceptions.py
- src/dsp_tools/models/sipi.py
- src/dsp_tools/utils/shared.py
- src/dsp_tools/utils/xml_upload.py
- testdata/json-project/test-project-systematic.json
> fix(xmlupload): print reason of error if a resource cannot be created, remodel BaseError (DEV-1977)

- docs/file-formats/xml-data-file.md
- src/dsp_tools/resources/start-stack/docker-compose.yml
- src/dsp_tools/utils/stack_handling.py
> chore: bump start-stack to 2023.04.03 (DEV-2117)

- src/dsp_tools/excel2xml.py
> chore(excel2xml): minor improvements (DEV-2152)

- test/e2e/test_00A1_import_scripts.py
- test/e2e/test_connection.py
- test/e2e/test_group.py
- test/e2e/test_listnode.py
- test/e2e/test_ontology.py
- test/e2e/test_project.py
- test/e2e/test_propertyclass.py
- test/e2e/test_resource.py
- test/e2e/test_resourceclass.py
- test/e2e/test_rosetta.py
- test/e2e/test_tools.py
- test/e2e/test_user.py
- test/e2e/test_xmlupload.py
- test/unittests/test_create_project.py
- test/unittests/test_excel2xml.py
- test/unittests/test_excel_to_json_lists.py
- test/unittests/test_excel_to_json_properties.py
- test/unittests/test_excel_to_json_resources.py
- test/unittests/test_generate_templates.py
- test/unittests/test_id_to_iri.py
- test/unittests/test_langstring.py
- test/unittests/test_shared.py
- test/unittests/test_value.py
- test/unittests/test_xmlupload.py
> chore: make all test files executable with pytest (DEV-2157)

- src/dsp_tools/models/exceptions.py
> chore: prevent access to unset attribute of BaseError (DEV-2158)

- src/dsp_tools/dsp_tools.py
> chore: log every CLI call to dsp-tools (DEV-2156)

- src/dsp_tools/resources/schema/data.xsd
- test/unittests/test_shared.py
- testdata/invalid-testdata/xml-data/duplicate-ark.xml
- testdata/invalid-testdata/xml-data/duplicate-iri.xml
- testdata/invalid-testdata/xml-data/empty-label.xml
- testdata/xml-data/test-data-systematic.xml
> chore: XML validation: resource's iri and ark must be unique, resource's label must not be empty (DEV-2154)

- src/dsp_tools/resources/start-stack/docker-compose.yml
- src/dsp_tools/utils/stack_handling.py
> chore: bump start-stack to 2023.05.01 (DEV-2164)

- src/dsp_tools/fast_xmlupload/upload_files.py
- src/dsp_tools/fast_xmlupload/upload_xml.py
- test/unittests/test_excel_to_json_resources.py
> chore: resolve CodeQL issues (DEV-2169)

- .github/dependabot.yml
> chore: enable automatic version updating by Dependabot (DEV-2170)

- .markdownlint.yml
- .yaml-lint.yml
- src/dsp_tools/dsp_tools.py
- src/dsp_tools/excel2xml.py
- src/dsp_tools/fast_xmlupload/process_files.py
- src/dsp_tools/fast_xmlupload/upload_files.py
- src/dsp_tools/fast_xmlupload/upload_xml.py
- src/dsp_tools/models/connection.py
- src/dsp_tools/models/exceptions.py
- src/dsp_tools/models/helpers.py
- src/dsp_tools/models/resource.py
- src/dsp_tools/models/resourceclass.py
- src/dsp_tools/utils/excel_to_json_lists.py
- src/dsp_tools/utils/excel_to_json_project.py
- src/dsp_tools/utils/excel_to_json_properties.py
- src/dsp_tools/utils/excel_to_json_resources.py
- src/dsp_tools/utils/id_to_iri.py
- src/dsp_tools/utils/project_create.py
- src/dsp_tools/utils/project_create_lists.py
- src/dsp_tools/utils/project_get.py
- src/dsp_tools/utils/project_validate.py
- src/dsp_tools/utils/rosetta.py
- src/dsp_tools/utils/shared.py
- src/dsp_tools/utils/stack_handling.py
- src/dsp_tools/utils/xml_upload.py
> chore: code formatting (DEV-2171)

- src/dsp_tools/excel2xml.py
- test/e2e/test_00A1_import_scripts.py
- test/unittests/test_excel2xml.py
> chore: move _derandomize_xsd_id (DEV-2186)

- test/e2e/test_rosetta.py
> test: fix e2e test of rosetta command (DEV-2212)

- .github/workflows/tests-on-push.yml
- src/dsp_tools/dsp_tools.py
- src/dsp_tools/fast_xmlupload/process_files.py
- src/dsp_tools/fast_xmlupload/upload_files.py
- src/dsp_tools/fast_xmlupload/upload_xml.py
- src/dsp_tools/utils/logging.py
- src/dsp_tools/utils/project_create.py
- src/dsp_tools/utils/project_create_lists.py
- src/dsp_tools/utils/shared.py
- src/dsp_tools/utils/xml_upload.py
> chore: don't configure logging statically (DEV-2183)

- .github/workflows/tests-on-push.yml
> chore: allow latest version of poetry again (DEV-2245)

- pyproject.toml
> chore: loosen python requirement, add py.typed marker (DEV-2278)

- pyproject.toml
- src/dsp_tools/models/group.py
- src/dsp_tools/models/listnode.py
- src/dsp_tools/models/model.py
- src/dsp_tools/models/ontology.py
- src/dsp_tools/models/permission.py
- src/dsp_tools/models/project.py
- src/dsp_tools/models/projectContext.py
- src/dsp_tools/models/propertyclass.py
- src/dsp_tools/models/propertyelement.py
- src/dsp_tools/models/resource.py
- src/dsp_tools/models/resourceclass.py
- src/dsp_tools/models/set_encoder.py
- src/dsp_tools/models/sipi.py
- src/dsp_tools/models/user.py
- src/dsp_tools/models/value.py
- src/dsp_tools/models/xmlallow.py
- src/dsp_tools/models/xmlpermission.py
- src/dsp_tools/models/xmlproperty.py
- src/dsp_tools/utils/project_create.py
- src/dsp_tools/utils/project_create_lists.py
- src/dsp_tools/utils/project_get.py
- test/e2e/test_project.py
- test/e2e/test_propertyclass.py
- test/e2e/test_resourceclass.py
- test/e2e/test_user.py
> chore: lint "models", part two (DEV-2287)

- src/dsp_tools/models/connection.py
- src/dsp_tools/utils/project_create.py
- src/dsp_tools/utils/project_get.py
> refactor: onto create (DEV-2298)

- src/dsp_tools/models/value.py
- src/dsp_tools/resources/schema/data.xsd
- testdata/xml-data/test-data-systematic.xml
> fix(xmlupload): allow colon in URL (DEV-2318)

- docs/developers/start-stack-command.md
- poetry.lock
- pyproject.toml
- src/dsp_tools/dsp_tools.py
- src/dsp_tools/resources/start-stack/start-stack-config.yml
- src/dsp_tools/utils/stack_handling.py
> chore: refactor start-stack (DEV-2397)

- src/dsp_tools/cli.py
- src/dsp_tools/fast_xmlupload/process_files.py
- src/dsp_tools/utils/excel2json/lists.py
- src/dsp_tools/utils/excel2json/properties.py
- src/dsp_tools/utils/excel2json/resources.py
- src/dsp_tools/utils/shared.py
- src/dsp_tools/utils/xmlupload/resource_multimedia.py
- src/dsp_tools/utils/xmlupload/upload_stashed_resptr_props.py
- src/dsp_tools/utils/xmlupload/upload_stashed_xml_texts.py
- src/dsp_tools/utils/xmlupload/write_diagnostic_info.py
- src/dsp_tools/utils/xmlupload/xmlupload.py
Background of this PR: I went through some log files and Terminal outputs of Noémi, in order to create a report for Ivan. Doing so, I missed some shortcomings. This PR adds some more time stamps and logging statements where I wish they would have been during Noémi's upload
> chore: add more logs and timestamps

- src/dsp_tools/commands/excel2json/properties.py
- test/unittests/commands/excel2json/test_properties.py
We follow a new convention where the file is read from top to bottom instead of bottom up.
The functions are reorganised.
According to the principle that code should speak for itself unnecessary comments were deleted.
No changes were made to the code.
> chore(excel2json-properties): reorganise file

- src/dsp_tools/commands/excel2json/utils.py
- src/dsp_tools/commands/fast_xmlupload/process_files.py
- test/unittests/commands/excel2json/test_utils.py
This is only very simple cases. There are more but are regarding class methods with a low confidence score by vulture. They require more investigation.
> chore: remove dead code with vulture

- src/dsp_tools/commands/xmlupload/check_consistency_with_ontology.py
- src/dsp_tools/commands/xmlupload/models/ontology_lookup_models.py
- src/dsp_tools/commands/xmlupload/ontology_client.py
- test/unittests/commands/xmlupload/test_ontology_lookup_models.py
This is in preparation to add further ontology consistency checks.
> refactor(ontology_client): make retrieval of ontologies more flexible (DEV-3308)

- src/dsp_tools/commands/xmlupload/resource_create_client.py
- src/dsp_tools/commands/xmlupload/xmlupload.py
These are some preliminary refactorings, so that the actual PR to make an xmlupload resumable can stay smaller.
> refactor: xmlupload

- docs/file-formats/xml-data-file.md
change of one word in the documentation
> docs: reformulate text-property and gui element

- src/dsp_tools/commands/excel2xml/excel2xml_lib.py
- test/unittests/commands/excel2xml/test_excel2xml_lib.py
> feat(excel2xml): if value is not valid, print warning instead of raising an error (only where it is possible) (DEV-3571)

- .pre-commit-config.yaml
This keeps blocking me from pushing stuff, I would like to version even incomplete files.
> refactor: ignore ARG001 (unused function argument) in .pre-commit-config.yaml

- src/dsp_tools/commands/excel2json/new_lists/make_new_lists.py
- src/dsp_tools/commands/excel2json/new_lists/models/input_error.py
- src/dsp_tools/commands/excel2json/new_lists/models/serialise.py
- test/unittests/commands/excel2json/new_lists/test_make_new_lists.py
- test/unittests/commands/excel2json/test_models_new_lists_serialise.py
The create code can never fail if the whole is run, because it is checked earlier, which stops the functions.
I made sure that regression cannot happen as I included the mistakes in the integration tests.
> refactor(excel2json-lists): remove unnecessary checks

- .github/workflows/tests-on-push.yml
Reverts dasch-swiss/dsp-tools#1152
> chore: Revert "chore: Fix tests not being executed on release-please branch"

- testdata/xml-data/test-data-systematic.xml
The custom permission "discouraged-edge-cases" was not referenced anywhere.
> test: make reference to custom permission in test data

- justfile
See https://just.systems/man/en/ignoring-errors.html
> chore(just): `just clean`: ignore errors
