dasch-swiss/dsp-tools

- .github/pull_request_template.md
- .github/workflows/ckeck-pr-title.yml
- .github/workflows/release-please.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
- docs/index.md
- setup.cfg
> chore: automate release process (DSP-1492)

- knora/dsp_tools.py
- knora/dsplib/models/helpers.py
- knora/dsplib/models/langstring.py
- knora/dsplib/models/listnode.py
- knora/dsplib/models/ontology.py
- knora/dsplib/models/propertyclass.py
- knora/dsplib/models/sipi.py
- knora/dsplib/utils/knora-schema-lists.json
- knora/dsplib/utils/knora-schema.json
- knora/dsplib/utils/onto_create_lists.py
- knora/dsplib/utils/onto_process_excel.py
- knora/dsplib/utils/onto_validate.py
- test/test_propertyclass.py
- testdata/test-data.xml
> fix: fix import ontology from salsah-export (DSP-1532)

- docs/dsp-tools-xmlupload.md
It is very important to know about this detail. Already two people ran into this, and it costed a lot of time to both of us. This warning is definitively needed.
> docs(dsp-tools-xmlupload): add Warning section (DSP-1693)

- .github/workflows/test.yml
- Makefile
- docs/changelog.md
- docs/requirements.txt
- mkdocs.yml
> docs: add changelog

- knora/dsp_tools.py
- knora/dsplib/models/sipi.py
- knora/dsplib/utils/xml_upload.py
- test/test_tools.py
> feat(verbose xml upload): use v option to print verbose output in XML upload (DSP-1797)

- docs/dsp-tools-create.md
I did some corrections in the "dsp-tools-create.md" documentation file.
> docs: fix wrong property attributes and typos

- docs/dsp-tools-create.md
I fixed property name and min-max value in the example
> docs: fix wrong property attributes and values

- docs/dsp-tools-create.md
- docs/dsp-tools-xmlupload.md
- knora/dsp_tools.py
- knora/dsplib/utils/onto_create_lists.py
- knora/dsplib/utils/onto_create_ontology.py
- knora/dsplib/utils/onto_validate.py
- knora/dsplib/utils/xml_upload.py
> feat(schema): add error codes for validation (DSP-1902)

- README.md
- docs/dsp-tools-information-for-developers.md
- knora/dsplib/models/BUILD.bazel
- knora/dsplib/models/listnode.py
- knora/dsplib/models/project.py
- knora/dsplib/models/propertyclass.py
- knora/dsplib/models/resourceclass.py
- knora/dsplib/utils/BUILD.bazel
- knora/dsplib/utils/onto_create_ontology.py
- knora/dsplib/utils/set_encoder.py
- knora/dsplib/utils/xml_upload.py
- test/e2e/test_tools.py
- testdata/test-onto.json
> fix: update dsp-tools to work with API version 16.0.0

- docs/dsp-tools-create.md
> docs: add time value section

- docs/dsp-tools-create.md
- knora/dsplib/utils/onto_create_ontology.py
> fix: inconsistencies in groups and projects (DEV-261)

- docs/dsp-tools-create.md
- knora/dsplib/schemas/ontology.json
- testdata/test-onto.json
> fix(schema): list root node needs a comments object (DEV-61)

- docs/dsp-tools-xmlupload.md
- knora/dsplib/models/value.py
> fix(boolean-values): allow 0 and 1 as boolean values (DEV-251)

- knora/dsplib/utils/xml_upload.py
> fix: print only unresolvable resptrs

- knora/dsplib/utils/xml_upload.py
> chore(xml-upload): print XML validation errors when xmlupload fails due to validation (DEV-387)

- docs/dsp-tools-usage.md
Add the validate option when xmlupload in the doc
> docs: add validate argparse info to xmlupload

- docs/dsp-tools-excel.md
- knora/dsplib/utils/excel_to_json_lists.py
- knora/dsplib/utils/expand_all_lists.py
resolves DEV-431
resolves also DEV-137
> refactor: excel to json list (DEV-431)

- knora/dsplib/models/resourceclass.py
- knora/dsplib/schemas/ontology.json
- knora/dsplib/utils/onto_create_ontology.py
- testdata/test-onto.json
> feat: make comments optional for new properties and resources (DEV-502)

- docs/dsp-tools-xmlupload.md
> docs: explain the interval-prop more precisely (DEV-566)

- docs/dsp-tools-create-ontologies.md
- docs/dsp-tools-create.md
- knora/dsplib/models/helpers.py
- knora/dsplib/utils/onto_create_ontology.py
> feat: improve prefix handling in json ontos (DEV-572)

- knora/dsplib/utils/onto_create_ontology.py
- test/unittests/test_create_ontology.py
> feat(onto creation): allow that resources and properties are not sorted by inheritance (DEV-626)

- knora/dsplib/utils/onto_create_ontology.py
> fix(groups): dsp-tools should not allow group creation if group name already in use (DEV-798)

- docs/dsp-tools-create.md
- knora/dsplib/models/project.py
- knora/dsplib/models/user.py
- knora/dsplib/utils/onto_get.py
> feat(get): get more infos from user (DEV-641)

- knora/dsplib/schemas/lists-only.json
- knora/dsplib/schemas/lists.json
- knora/dsplib/schemas/ontology.json
- knora/dsplib/schemas/properties-only.json
- knora/dsplib/schemas/resources-only.json
With this, VS Code now validates the json while working on it, which is very handy.
resolves DEV-848
> refactor(json-schema): change JSON schema version to draft-07 (DEV-848)

- docs/dsp-tools-xmlupload.md
> docs: fix typos in documentation (DEV-849)

- knora/dsplib/models/resource.py
- knora/dsplib/utils/xml_upload.py
- testdata/test-data-systematic.xml
> fix: a slight modification to test-data.xml makes the tests fail (DEV-1140)

- knora/dsp_tools.py
- knora/dsplib/utils/onto_create_lists.py
- knora/dsplib/utils/onto_validate.py
- knora/dsplib/utils/shared.py
- knora/dsplib/utils/xml_upload.py
- test/e2e/test_tools.py
- test/unittests/test_create_project.py
- test/unittests/test_shared.py
- testdata/test-data-invalid-resource-tag.xml
- testdata/test-project-circular-ontology.json
- testdata/test-project-invalid-super-property.json
> fix: xml validation (DEV-1360)

- .github/workflows/release-please.yml
> chore: fix release-please (DEV-1396)

- knora/dsplib/models/helpers.py
- knora/dsplib/utils/xml_upload.py
- testdata/test-data-systematic.xml
> chore(xmlupload): improve error message when syntax for referencing ontos is wrong (DEV-1399)

- docs/dsp-tools-create.md
> docs: user needs to be project member to become project admin (DEV-1383)

- .github/pull_request_template.md
- .github/workflows/check-pr-title.yml
- README.md
> docs(readme): explain handling of git submodules (DEV-1502)

- .github/pull_request_template.md
- .github/workflows/check-pr-title.yml
> chore: fix regex for PR title (DEV-1504)

- docs/dsp-tools-create-ontologies.md
- docs/dsp-tools-xmlupload.md
> docs: text values: describe which combinations of gui_element and encoding are desirable (DEV-1521)

- docs/dsp-tools-usage.md
- knora/dsp_tools.py
- knora/dsplib/utils/xml_upload.py
- test/e2e/test_0123_import_scripts.py
- test/e2e/test_tools.py
> chore(xmlupload): add metrics flag (DEV-1512)

- knora/dsplib/models/resource.py
- knora/dsplib/utils/xml_upload.py
> fix(xmlupload): prevent crash + improve error message when cardinalities are wrong (DEV-1559)

- README.md
- knora/dsplib/utils/stack_handling.py
> fix(start-stack): copy docker folder to user's home directory (DEV-1581)

- src/dsp_tools/docker/docker-compose.yml
- src/dsp_tools/utils/stack_handling.py
> chore: bump versions of start-stack to 2023.01.02 (DEV-1652)

- src/dsp_tools/models/propertyclass.py
> fix(get): prevent invalid gui_element "Pulldown" (DEV-1781)

- src/dsp_tools/utils/shared.py
- src/dsp_tools/utils/xml_upload.py
- test/unittests/test_shared.py
- testdata/xml-data/test-data-systematic.xml
> fix(xmlupload): legitimate html-escapes in utf8-texts don't raise a validation error any more (DEV-1936)

- .markdownlint.yml
- README.md
- docs/cli-commands.md
- docs/developers/git-submodules.md
- docs/developers/mkdocs.md
- docs/excel2xml-module.md
- docs/file-formats/excel2json.md
- docs/file-formats/json-project/caveats.md
- docs/file-formats/json-project/ontologies.md
- docs/file-formats/json-project/overview.md
- docs/file-formats/xml-data-file.md
- docs/internal/fast-xmlupload.md
- src/dsp_tools/excel2xml.py
- src/dsp_tools/utils/excel_to_json_lists.py
- src/dsp_tools/utils/excel_to_json_properties.py
- src/dsp_tools/utils/excel_to_json_resources.py
- src/dsp_tools/utils/id_to_iri.py
- src/dsp_tools/utils/project_create.py
- src/dsp_tools/utils/rosetta.py
- src/dsp_tools/utils/shared.py
- test/e2e/test_00A1_import_scripts.py
> chore: reformat code (DEV-2263)

- src/dsp_tools/resources/start-stack/docker-compose.yml
- src/dsp_tools/utils/stack_handling.py
> chore: bump start-stack to 2023.06.02 (DEV-2312)

- src/dsp_tools/resources/start-stack/docker-compose.yml
@jnussbaum and/or @Nora-Olivia-Ammann could you check if the workflow with fast-xmlupload and ingest works with that.  
I can say for sure that both images have access to the images; what I'm not so sure about is if all the plumbing is quite correct. But I wasn't sure how to trigger this workflow, so I thought I'd leave this up to you :)
> chore: integrate DSP-INGEST in start-stack

- src/dsp_tools/resources/start-stack/docker-compose.yml
According to the "DSP Releases" chat, they decided to use an older version of DSP-APP for today's deployment, because they detected a bug in the newer version.
> chore(start-stack): downgrade DSP-APP

- src/dsp_tools/analyse_xml_data/construct_and_analyze_graph.py
- src/dsp_tools/analyse_xml_data/models.py
- test/unittests/test_analyse_xml_data/test_construct_and_analyze_graph.py
- testdata/xml-data/circular-references/analyse_circles_in_xml.py
The complicated type annotation `list[tuple[int, int, XMLLink | ResptrLink]]` is replaced by a new model: `class Edge` in `models.py`
> refactor: use class Edge instead of complicated type annotation

- src/dsp_tools/utils/xmlupload/project_client.py
Note: This code is not yet in use, but it will be used in a separate PR. I just try to keep things as much to the point, as possible, so that the PRs stay small
> refactor: add a client for project related requests (DEV-2890)

- src/dsp_tools/models/xmlresource.py
- src/dsp_tools/utils/xmlupload/resource_multimedia.py
- src/dsp_tools/utils/xmlupload/xmlupload.py
Another little PR to pave the way for my upcoming PR
> refactor: add specific model for bitstream information (DEV-2893)

- docs/cli-commands.md
- src/dsp_tools/cli.py
- src/dsp_tools/excel2xml.py
- test/unittests/test_cli_with_mock.py
- test/unittests/test_excel2xml.py
https://linear.app/dasch/issue/DEV-2917/
> chore(excel2xml): suppress irrelevant warnings, turn non-fatal errors into warnings (DEV-2917)

- src/dsp_tools/commands/id2iri.py
- test/fast_xmlupload/test_fast_xmlupload.py
- test/unittests/commands/test_id2iri.py
- test/unittests/commands/xmlupload/test_check_consistency_with_ontology_high_level.py
In some places, dsp-tools uses defaults for mutable class attributes, which is a bad idea: https://docs.astral.sh/ruff/rules/mutable-class-default/
> chore: avoid mutable default values in class attributes (DEV-3234)

- src/dsp_tools/utils/xml_utils.py
- src/dsp_tools/utils/xml_validation.py
Currently for the validate xml, the comments were not removed. This caused problems when finding the `encodings` attributes. However, we need the namespaces for the first validation step. Therefore a function was created that only parses the file and removes the comments.
> chore(xmlupload): improve parse xml function

- src/dsp_tools/utils/xml_utils.py
- test/unittests/commands/xmlupload/test_xmlupload.py
- test/unittests/utils/test_xml_utils.py
This is in preparation to turn them into pytests, so that the diff is manageable.
No changes were made to the content.
The first part of the tests were moved to a new file as the previous location did not mirror the location in the src
> chore(test_xmlupload): separate tests

- src/dsp_tools/commands/excel2xml/excel2xml_lib.py
- test/unittests/commands/excel2xml/test_excel2xml_lib.py
This is allowed in text: `<br></br>`
Fix to allow this: `<br/>`
> feat(excel2xml): allow for single tags in XML text (DEV-3427)

- .github/workflows/tests-on-push.yml
- src/dsp_tools/utils/logger_config.py
- test/e2e/commands/test_create_get_xmlupload.py
- test/e2e/conftest.py
<p><a href="https://linear.app/dasch/issue/DEV-3436/make-logging-available-after-ci-test-runs">DEV-3436 make logging available after CI test runs</a></p>
> chore(ci): make logging file available after e2e test (DEV-3436)

- src/dsp_tools/resources/start-stack/docker-compose.yml
From this PR (https://github.com/dasch-swiss/dsp-api/pull/3165) on, DSP-API needs a new environment variable.
> chore: set api log level in docker-compose.yml

- .github/workflows/tests-on-push.yml
- pyproject.toml
- src/dsp_tools/commands/excel2xml/excel2xml_cli.py
until now, the `ruff format .` in the CI checks didn't really check anything. Ruff must be called with the `--check` flag in order to exit with non-0 if a wrong formatting is found.
> chore(ci): fix ruff format checking

- src/dsp_tools/resources/start-stack/docker-compose.yml
As per https://docs.docker.com/compose/networking/, `docker compose` sets up a default network, and each container joins that default network.
> chore(start-stack): remove network from docker-compose.yml

- src/dsp_tools/resources/start-stack/docker-compose.yml
Use a docker volume to store the ingest sqlite file persistently.
From the upcoming dsp-ingest release on the service requires an sqlite file to start.
The location is configured with the jdbc location.
The service will create and maintain that file by itself.
In order to retain the database's state it is stored in a docker volume.
This is the same change in the dsp-api setup:
https://github.com/dasch-swiss/dsp-api/pull/3304/files
> chore: Add db configuration to ingest container

- src/dsp_tools/commands/xmlupload/models/ingest.py
- test/unittests/commands/xmlupload/models/test_ingest.py
In order to support filename containing special characters the filename in the url for the request to the ingest service must be properly url encoded.
> fix: Urlencode filenames when uploading files to ingesta (DEV-3865)

- test/e2e/conftest.py
- test/e2e/setup_testcontainers.py
The changes introduced by #1042 and #1039 should also be applied to the testcontainers.
> refactor(test): renaming

- .pre-commit-config.yaml
In principle, the linter ignore lists should be the same in all places. This means, if a rule is ignored in the GitHub CI, it should also be ignored in the pre-commit-hooks, and vice versa. 
A while ago, `ARG001` was added to the ignore list in the pre-commit-hooks, because during WIP, it's more convenient if this rule is not checked. That seems logical. 
However, there is a problem: 3 files in our codebase contain an inline-ignore (`# noqa: ARG001 (unused argument)`). Whenever one of these files is modified, the pre-commit-hooks fail, because they don't allow an inline-comment for an already ignored rule. When this error occurs, it is very difficult to understand what is going on.
It would be cleaner to have the same ignore lists in all places. During WIP, one can commit in the Terminal …
> chore: don't ignore ARG001 in pre-commit hooks

- src/dsp_tools/commands/ingest_xmlupload/bulk_ingest_client.py
- src/dsp_tools/commands/ingest_xmlupload/create_resources/apply_ingest_id.py
Currently, absolute paths are always converted to relative ones, but in most cases, this is detrimental. The conversion should only happen if the absolute path cannot be found in the mapping CSV.
> fix(ingest-xmlupload): only convert absolute path from mapping CSV to relative path if necessary

- src/dsp_tools/commands/validate_data/sparql/value_shacl.py
- test/unittests/commands/validate_data/fixtures_onto.py
- test/unittests/commands/validate_data/test_sparql_value_shacl.py
```
<http://0.0.0.0:3333/ontology/9999/onto/v2#testDecimalSimpleText> a owl:ObjectProperty ;
rdfs:label "Test Decimal" ;
ns1:isEditable true ;
ns1:isResourceProperty true ;
ns1:objectType ns1:DecimalValue ;
ns2:guiElement ns2:SimpleText ;
rdfs:subPropertyOf ns1:hasValue .
```
The `SimpleText` gui element can be used with non `TextValue` value types.
> fix(validate-data): prevent SimpleText Class shape to be used at the wrong place (DEV-4224)

- src/dsp_tools/commands/validate_data/sparql/cardinality_shacl.py
- src/dsp_tools/commands/validate_data/sparql/value_shacl.py
- test/integration/commands/validate_data/test_reformat_input.py
- test/integration/commands/validate_data/test_validate_data.py
- testdata/validate-data/data/content_correct.xml
- testdata/validate-data/data/minimal_correct.xml
Excluding properties through the gui-order is not a good idea because it is optional.
Better is through the triple: `?propRestriction knora-api:isEditable true .`
However, file values are editable too but are not yet implemented. Until file values are implemented it is easiest exclude properties through the gui-order.
> fix(validate-data): revert to exclusion of properties through gui-order (DEV-4279)

- justfile
Apparently, just doesn't support the `**` glob pattern, so the `find` command is necessary
> chore: fix `just clean` recipe

- src/dsp_tools/resources/start-stack/docker-compose.yml
- src/dsp_tools/resources/start-stack/dsp-app-config.json
In the docker container of DSP-APP on a server, there are several config files, which are copied from the [DSP-APP repo](https://github.com/dasch-swiss/dsp-das/blob/eca422202fd5653569b6cff2abdf6a327aa2b49f/apps/dsp-app/src/config/): 
- `/public/config/config.test-server.json`
- `/public/config/config.prod.json`
- etc.
On our servers, the deployment scripts of ops-deploy copy [this file](https://github.com/dasch-swiss/ops-deploy/blob/main/roles/dsp-deploy/templates/app/conf/config-v11.json.j2) to `/home/knora/DSP/admin/conf/config.json`. This file contains an entry featureFlags.allowEraseProjects. The `/home/knora/DSP/docker-compose.yml` maps this file to `/public/config/config.prod.json` inside the DSP-APP container.
The confusing part is that inside the DSP-APP container, several config …
> fix(start-stack): allow erasing project on localhost (DEV-4422)

- src/dsp_tools/commands/project/create/parse_project.py
- src/dsp_tools/commands/project/create/project_create.py
- src/dsp_tools/commands/project/models/parsed_project.py
- src/dsp_tools/commands/project/models/project_definition.py
- test/unittests/commands/project/test_parse_project.py
New:
- `ParsedProject` object contains metadata and the ontologies, they are no longer separate
Changes:
- Moved code around, no changes in content or logic
> refactor(create): change structure of parsed project

- src/dsp_tools/xmllib/helpers.py
- test/unittests/xmllib/test_helpers.py
@Notheturtle @Nora-Olivia-Ammann While working with `find_date_in_string()`, I thought that the documentation could be clarified. Do you think that's helpful, or rather an unnecessary bloating of the docs?
> docs(xmllib): clarify that find_date_in_string() finds only 1 date

- src/dsp_tools/commands/validate_data/api_clients.py
- src/dsp_tools/utils/request_utils.py
Logging the content of very large responses, for example when knora-api is requested, unnecessary blows up logging files.
> refactor: add option to exclude request response text in logging

- justfile
`find ... -exec rm -rf {} \;` executes `rm -rf` once per match. This is not only inefficient, it can also lead to errors like this: `find: ./test/integration/utils/xml_parsing/__pycache__: No such file or directory`. 
This error occurs because the `find` command is trying to act on a directory that no longer exists. This typically happens when `rm -rf` deletes the directory before `find` completes its traversal.
Use `find ... -exec rm -rf {} +` instead.
This is not directly related to the above problem, but it came to my mind that it would be good to restart the daemon when we execute `just clean`.
> chore: optimise `just clean`

- .github/workflows/test-latest-be.yml
- .github/workflows/tests-on-push.yml
Currently, a PR opened from a fork cannot be merged, because the mandatory checks aren't triggered (see https://github.com/dasch-swiss/dsp-tools/pull/1606). This is probably due to the wrong triggering conditions. 
`on: pull_request` makes sure that the tests are triggered if a PR is opened, synchronized, or reopened (see https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request)
> chore: PR checks should be triggered on PRs from forks
